### ISSUE TITLE
NatureRemoのRest_commandについて

### ISSUE THREAD

**Issue by Chabiichi** [k1asa/hass-config#1]
初めまして。GithubもHAも初心者で右も左もわからない者です。初歩的な質問ですみません。
NatureRemoのAuthorizationヘッダーの'secret.yaml'の書式は
`nature_key: "Bearer ******"`
で良いのでしょうか？
また、エアコンをオンにするコマンドのPayloadは温度のみですが、モードの切り替えなどはどのようにしているのでしょうか？
このような質問をこちらで書いても良いのかどうかもわかりません。ルール違反でしたらご指摘いただけると幸いです。

**Comment by k1asa** [comment]
gitの使い方もわからず全く気づけてなくてすみません。
トラブルは解決されていますでしょうか…。
まだでしたらとできる限りの回答させていただきます。

自分はダブルクオーテーションなしで記載しています

`nature_key: Bearer *******************`

**Comment by Chabiichi** [comment]
ご回答ありがとうございます。
secret.yaml のトークンの記述やエアコンの設定については解決しました。ありがとうございました。
今悩んでいるのはAPIで調光を行う方法です。いろいろ調べてますがTemplate Lightを使えば出来るようですが、私にはさっぱりわかりません。

**Comment by k1asa** [comment]
最初のご質問は解決とのことで一応クローズしますね。

nature remoのapiを用いて、どんな信号を送ってるのかを確認する必要がありますね。
リモコンでの調光がボタンを連続して押すタイプならどうしてもそのボタン一回分の送信を
繰り返すことにもなりそうです。
もし続くようなら新しいスレッドたててくださいな
